WITH CTE AS (

SELECT
TO_TIMESTAMP(STARTED_AT) AS started_at, 
date(TO_TIMESTAMP(STARTED_AT)) as date_started_at,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT, 
CASE 
    WHEN LOWER(DAYNAME(TO_TIMESTAMP(STARTED_AT))) in ('sat', 'sun') THEN 'WEEKEND' 
    ELSE 'BUSINESSDAY' 
    END AS DAY_TYPE, 
CASE 
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2) THEN 'WINTER' 
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5) THEN 'SPRING' 
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8) THEN 'SUMMER' 
    ELSE 'AUTUM' END AS STATION_OF_YEAR        

FROM {{ source('demo', 'bike') }}

)

SELECT 
* 
FROM CTE